# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tpot < Formula
  desc "tpot is a simple tool to access teleport web UI from terminal"
  homepage "https://github.com/adzimzf/tpot"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/adzimzf/tpot/releases/v0.0.3/tpot_0.0.3_macOS_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d664350ab43c7a7eec93598c1fee8fdc1bc5eeead4108b58462bf502f3f1277a"

      def install
        bin.install "program"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/adzimzf/tpot/releases/v0.0.3/tpot_0.0.3_macOS_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "60ccb79048dcdbe23d279abbe87f075c78e1460373b8176479b6ba3ca382b8d3"

      def install
        bin.install "program"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/adzimzf/tpot/releases/v0.0.3/tpot_0.0.3_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e72a37719fa2af4455aeae647f147f6539f99d171bc4f765968ba9f97514c48c"

      def install
        bin.install "program"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/adzimzf/tpot/releases/v0.0.3/tpot_0.0.3_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "581f02ad64d9e236fbda375cbb952fd2fb6fd165af464a14b7311a2d55923235"

      def install
        bin.install "program"
      end
    end
  end

  head "https://github.com/adzimzf/tpot.git"

  depends_on "git"
  depends_on "zsh" => :optional

  test do
    system "#{bin}/tpot --version"
  end
end
