# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Tpot < Formula
  desc "tpot is a simple tool to access teleport web UI from terminal"
  homepage "https://github.com/adzimzf/tpot"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/adzimzf/tpot/releases/v0.0.3/tpot_0.0.3_macOS_arm64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "fe9a4d48ff751b00d5887cf02fe976ee6caaad45205839d727ab820477e90959"

      def install
        bin.install "program"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/adzimzf/tpot/releases/v0.0.3/tpot_0.0.3_macOS_amd64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "de14504f239d88a80bd618cd8553cfb9a8b816b34a3fdb227bd67b59fdf5a237"

      def install
        bin.install "program"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/adzimzf/tpot/releases/v0.0.3/tpot_0.0.3_linux_arm64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "1a7c20478fd9ee1f6f30f3501ef312808893387d31153eba03f63b6581f1b8f7"

      def install
        bin.install "program"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/adzimzf/tpot/releases/v0.0.3/tpot_0.0.3_linux_amd64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "cf41b5fd0aa4ab4b100f259335d6c04adf76e36662696307db4927ff38b1b79e"

      def install
        bin.install "program"
      end
    end
  end

  head "https://github.com/adzimzf/tpot.git"
  ...

  depends_on "git"
  depends_on "zsh" => :optional

  plist_options :startup => false

  def plist; <<~EOS
    ...

  EOS
  end

  test do
    system "#{bin}/tpot --version"
    ...
  end
end
