# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tpot < Formula
  desc "tpot is a simple tool to access teleport web UI from terminal"
  homepage "https://github.com/adzimzf/tpot"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/adzimzf/tpot/releases/download/v0.0.4/tpot_0.0.4_macOS_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f4e5f70f6c28ba9b434adccbda1fcd155e9735c5e7cea66e4ca687b04c8fd6ac"

      def install
        bin.install "bin/tpot"
        zsh_completion.install "completions/zsh/_tpot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/adzimzf/tpot/releases/download/v0.0.4/tpot_0.0.4_macOS_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d6e8b88f3ff854697195424e49aba7d34715f9f033e08d147fae470ba18a01f3"

      def install
        bin.install "bin/tpot"
        zsh_completion.install "completions/zsh/_tpot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adzimzf/tpot/releases/download/v0.0.4/tpot_0.0.4_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e576e2de125b160b2b6e751c5c26436e56784c5fd178191f53ba2e5f99864637"

      def install
        bin.install "bin/tpot"
        zsh_completion.install "completions/zsh/_tpot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/adzimzf/tpot/releases/download/v0.0.4/tpot_0.0.4_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "817cab132bed7a6ccace868764d7340d2d08c4224fa9896aadd512648a809023"

      def install
        bin.install "bin/tpot"
        zsh_completion.install "completions/zsh/_tpot"
      end
    end
  end

  head "https://github.com/adzimzf/tpot.git"

  depends_on "tsh" => :optional
  depends_on "zsh" => :optional

  test do
    system "#{bin}/tpot --version"
  end
end
