# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tpot < Formula
  desc "tpot is a simple tool to access teleport web UI from terminal"
  homepage "https://github.com/adzimzf/tpot"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adzimzf/tpot/releases/download/v0.0.3/tpot_0.0.3_macOS_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "9e16a07b9e8f437cfcd8f22814ec979693ec88fb311964d51f8d8e365fafea37"

      def install
        bin.install "bin/tpot"
        zsh_completion.install "completions/zsh/_tpot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adzimzf/tpot/releases/download/v0.0.3/tpot_0.0.3_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f6fe677c3baa291d5b781ba37218ec737629f3497aa76f2d7ca3df27192d224e"

      def install
        bin.install "bin/tpot"
        zsh_completion.install "completions/zsh/_tpot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/adzimzf/tpot/releases/download/v0.0.3/tpot_0.0.3_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "17cd6a3540fb88a5c23831586d4f4ffa4a1591d031e2576494cfd530dfc00394"

      def install
        bin.install "bin/tpot"
        zsh_completion.install "completions/zsh/_tpot"
      end
    end
  end

  head "https://github.com/adzimzf/tpot.git"

  depends_on "tsh" => :optional
  depends_on "zsh" => :optional

  test do
    system "#{bin}/tpot --version"
  end
end
