# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tpot < Formula
  desc "tpot is a simple tool to access teleport web UI from terminal"
  homepage "https://github.com/adzimzf/tpot"
  version "0.0.5"

  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/adzimzf/tpot/releases/download/v0.0.5/tpot_0.0.5_macOS_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f82d3dd8f3c56558b81e8e43230783669e999ea9831cc94b79cad9b14306719a"

      def install
        bin.install "bin/tpot"
        zsh_completion.install "completions/zsh/_tpot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/adzimzf/tpot/releases/download/v0.0.5/tpot_0.0.5_macOS_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "fbbefd13ff33f6792c1ace323376828d9b1224163a6d84e86bdc0cf669a6f8a8"

      def install
        bin.install "bin/tpot"
        zsh_completion.install "completions/zsh/_tpot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adzimzf/tpot/releases/download/v0.0.5/tpot_0.0.5_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ca94f66249a4ca85dc3f4b92d12277531b09c0844c090df5d60b811ed96b0a56"

      def install
        bin.install "bin/tpot"
        zsh_completion.install "completions/zsh/_tpot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/adzimzf/tpot/releases/download/v0.0.5/tpot_0.0.5_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "40dc87182bccf59b5c05bc656b13fabc4add30efcc02c6220c1e7f89738debfa"

      def install
        bin.install "bin/tpot"
        zsh_completion.install "completions/zsh/_tpot"
      end
    end
  end

  head "https://github.com/adzimzf/tpot.git"

  test do
    system "#{bin}/tpot --version"
  end
end
